# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    lottoWsdl: http://serwis.mobilotto.pl/mapi/index.php?soap=ssv1.wsdl

services:
    dwr_lotto_client:
        class: Dwr\LottoClientBundle\Service\LottoClient
        arguments: ["%lottoWsdl%"]
